[project]
# The name of your game's executable. This should only contain a-z, A-Z, 0-9, _ or -.
name = "FarmingVillage"
# The game's title. This will show up in the tile bar of your executable.
title = "Farming Village"
version = "0.1.0"
authors = ["Kevin Fischer <kfischer_okarin@yahoo.co.jp>"]
icon = "metadata/icon.png"
compile_ruby = false

[dragonruby]
version = "4.0"
edition = "pro"

[dependencies]

[dependencies.dr_base_framework]
repo = "https://github.com/kfischer-okarin/dr_base_framework.git"
tag = "2022.12.13"

[itch]
# The Project URL you set when you created the game on Itch.io. https://my-username.itch.io/my-game.
# This will also be the name of your build files, so fill it out even if you aren't uploading to Itch.io.
url = "farming-village"
# Your username on Itch.io.
username = "kfischer-okarin"
