# This file was automatically @generated by Smaug.
# Do not manually edit this file. Edit Smaug.toml instead.

require "smaug/dr_base_framework/lib/dr_base_framework/animations.rb"
require "smaug/dr_base_framework/lib/dr_base_framework/animations/asesprite_json.rb"
require "smaug/dr_base_framework/lib/dr_base_framework/animated_sprite.rb"

